# 定义服务
services:
  # 数据库服务
  db:
    # 使用 PostgreSQL 15 官方镜像
    image: postgres
    # 容器退出时自动重启
    restart: always
    # 设置环境变量
    environment:
      POSTGRES_USER: admin        # 设置 PostgreSQL 管理员用户名
      POSTGRES_PASSWORD: admin    # 设置 PostgreSQL 管理员密码
      POSTGRES_DB: mydatabase     # 创建默认数据库
    # 端口映射：主机端口:容器端口
    ports:
      - "5432:5432"  # 将主机的5432端口映射到容器的5432端口
    # 挂载卷，用于数据持久化
    volumes:
      - postgres-data:/var/lib/postgresql/data  # 将数据库数据存储在命名卷中
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

# 定义命名卷
volumes:
  postgres-data:  # 创建名为 postgres-data 的卷，用于持久化数据库数据